import {Link} from 'react-router-dom';import useProducts from '../hooks/useProducts.js';import ProductGrid from '../components/ProductGrid.jsx';import Newsletter from '../components/Newsletter.jsx';
const reviews=[['Aarav','The oversized tee fits exactly like the photos. Great fabric.'],['Meera','Face wash is gentle and my skin feels balanced.'],['Rohan','Fast delivery and the grooming kit made a perfect gift.']];
function Section({title,link,products,loading}){return <section className="container-x mt-16"><div className="mb-6 flex items-end justify-between"><h2 className="h-display text-2xl sm:text-3xl">{title}</h2>{link&&<Link to={link} className="text-sm font-medium text-brand underline">View all</Link>}</div><ProductGrid products={products.slice(0,4)} loading={loading}/></section>}
export default function Home(){const {products:all,loading}=useProducts();const pick=f=>all.filter(f);
return <><section className="container-x grid items-center gap-8 py-12 md:grid-cols-2"><div><h1 className="h-display text-4xl leading-tight sm:text-6xl">Dress well. Look after yourself.</h1><p className="mt-4 max-w-md text-ink/70">Everyday clothing and grooming essentials, chosen for quality you can feel.</p><div className="mt-6 flex gap-3"><Link to="/clothing" className="btn-primary">Shop clothing</Link><Link to="/self-grooming" className="btn-outline">Shop grooming</Link></div></div>
 <div className="grid grid-cols-2 gap-4"><Link to="/clothing" className="flex aspect-[3/4] items-end rounded-3xl bg-brand p-5 text-xl text-white h-display">Clothing</Link><Link to="/self-grooming" className="mt-8 flex aspect-[3/4] items-end rounded-3xl bg-sand p-5 text-xl h-display">Self Grooming</Link></div></section>
 <Section title="Featured clothing" link="/clothing" loading={loading} products={pick(p=>p.featured&&p.category==='Clothing')}/>
 <Section title="Featured self grooming" link="/self-grooming" loading={loading} products={pick(p=>p.featured&&p.category==='Self Grooming')}/>
 <Section title="Best sellers" link="/shop" loading={loading} products={pick(p=>p.bestseller)}/>
 <Section title="New arrivals" link="/shop" loading={loading} products={pick(p=>p.newArrival)}/>
 <section className="container-x mt-16"><div className="rounded-3xl bg-sand p-10 text-center"><h2 className="h-display text-3xl">Free delivery over ₹999</h2><p className="mt-1">Easy 7-day returns on every order.</p></div></section>
 <section className="container-x mt-16"><h2 className="h-display mb-6 text-2xl sm:text-3xl">What customers say</h2><div className="grid gap-4 sm:grid-cols-3">{reviews.map(([n,t])=><blockquote key={n} className="rounded-2xl bg-white p-6"><p>{t}</p><footer className="mt-3 text-sm font-medium">{n}</footer></blockquote>)}</div></section><Newsletter/></>}
