import {useEffect,useState} from 'react';import {Link,useNavigate,useParams} from 'react-router-dom';import {Truck,RotateCcw,Heart} from 'lucide-react';
import {getProductById} from '../services/productService.js';import useProducts from '../hooks/useProducts.js';import SafeImage from '../components/SafeImage.jsx';import Rating from '../components/Rating.jsx';import Price from '../components/Price.jsx';import QuantitySelector from '../components/QuantitySelector.jsx';import ProductGrid from '../components/ProductGrid.jsx';
import {useCart} from '../context/CartContext.jsx';import {useWishlist} from '../context/WishlistContext.jsx';import {related} from '../utils/productUtils.js';
import {NotFound} from './Info.jsx';
export default function ProductDetails(){const {productId}=useParams();const nav=useNavigate();const {add}=useCart();const {has,toggle}=useWishlist();const {products}=useProducts();
const [p,setP]=useState(undefined);const [img,setImg]=useState(0);const [size,setSize]=useState(null);const [color,setColor]=useState(null);const [qty,setQty]=useState(1);const [err,setErr]=useState('');
useEffect(()=>{setP(undefined);setImg(0);setQty(1);setErr('');getProductById(productId).then(x=>{setP(x);setSize(null);setColor(x?.colors?.[0]||null)})},[productId]);
if(p===undefined)return <div className="container-x py-20" aria-busy="true"><div className="h-96 animate-pulse rounded-2xl bg-ink/10"/></div>;
if(!p)return <NotFound product/>;
const imgs=p.images?.length?p.images:[null];const d=p.details;
const addNow=(go)=>{if(p.sizes?.length&&!size){setErr('Please select a size.');return}add(p,{size,color,qty});if(go)nav('/cart')};
return <div className="container-x py-10"><nav className="mb-4 text-sm text-ink/60"><Link to="/">Home</Link> / <Link to={p.category==='Clothing'?'/clothing':'/self-grooming'}>{p.category}</Link> / {p.name}</nav>
<div className="grid gap-10 md:grid-cols-2"><div><SafeImage src={imgs[img]} alt={p.name} className="aspect-[4/5] w-full rounded-2xl"/><div className="mt-3 flex gap-2">{imgs.map((s,i)=><button key={i} aria-label={`Image ${i+1}`} onClick={()=>setImg(i)} className={`h-16 w-16 overflow-hidden rounded-lg border-2 ${i===img?'border-brand':'border-transparent'}`}><SafeImage src={s} alt="" className="h-full w-full"/></button>)}</div></div>
<div className="space-y-5"><p className="text-sm text-ink/50">{p.subCategory}</p><h1 className="h-display text-3xl">{p.name}</h1><Rating value={p.rating} count={p.reviews}/><Price {...p} large/><p className="text-ink/70">{p.description}</p>
{p.sizes?.length>0&&<fieldset><legend className="mb-2 font-medium">Size</legend><div className="flex flex-wrap gap-2">{p.sizes.map(s=><button key={s} aria-pressed={size===s} onClick={()=>{setSize(s);setErr('')}} className={`h-10 min-w-10 rounded-full border px-3 text-sm ${size===s?'border-brand bg-brand text-white':'border-ink/20'}`}>{s}</button>)}</div>{err&&<p role="alert" className="mt-2 text-sm text-red-600">{err}</p>}</fieldset>}
{p.colors?.length>0&&<fieldset><legend className="mb-2 font-medium">Color: {color}</legend><div className="flex flex-wrap gap-2">{p.colors.map(c=><button key={c} aria-pressed={color===c} onClick={()=>setColor(c)} className={`rounded-full border px-3 py-1 text-sm ${color===c?'border-brand bg-brand text-white':'border-ink/20'}`}>{c}</button>)}</div></fieldset>}
{d&&<dl className="space-y-3 rounded-2xl bg-white p-5 text-sm"><div><dt className="font-medium">Skin / hair type</dt><dd>{d.skinType}</dd></div><div><dt className="font-medium">Size</dt><dd>{d.size}</dd></div><div><dt className="font-medium">Ingredients</dt><dd>{d.ingredients}</dd></div><div><dt className="font-medium">Benefits</dt><dd><ul className="list-disc pl-5">{d.benefits.map(b=><li key={b}>{b}</li>)}</ul></dd></div><div><dt className="font-medium">How to use</dt><dd>{d.howToUse}</dd></div></dl>}
{p.specs&&<dl className="space-y-1 rounded-2xl bg-white p-5 text-sm">{Object.entries(p.specs).map(([k,v])=><div key={k} className="flex justify-between"><dt className="text-ink/60">{k}</dt><dd>{v}</dd></div>)}</dl>}
<div className="flex flex-wrap items-center gap-3"><QuantitySelector value={qty} onChange={setQty} max={p.stock}/><button className="btn-primary flex-1" disabled={p.stock<1} onClick={()=>addNow(false)}>{p.stock<1?'Out of stock':'Add to cart'}</button><button className="btn-outline flex-1" disabled={p.stock<1} onClick={()=>addNow(true)}>Buy now</button><button aria-pressed={has(p.id)} aria-label="Toggle wishlist" onClick={()=>toggle(p.id)} className="btn-outline"><Heart size={18} className={has(p.id)?'fill-red-500 text-red-500':''}/></button></div>
<ul className="space-y-2 text-sm text-ink/70"><li className="flex gap-2"><Truck size={18}/>Free delivery over ₹999. Delivered in 3–5 days.</li><li className="flex gap-2"><RotateCcw size={18}/>7-day easy returns and refunds.</li></ul></div></div>
<section className="mt-16"><h2 className="h-display mb-4 text-2xl">Reviews</h2><p className="rounded-2xl bg-white p-6 text-ink/70">{p.reviews} customers rated this {p.rating}/5. Written reviews will appear here once a backend is connected.</p></section>
<section className="mt-16"><h2 className="h-display mb-4 text-2xl">Related products</h2><ProductGrid products={related(products,p)}/></section></div>}
